export const PRODUCT_LIST_SUCCESS = 'PRODUCT_LIST_SUCCESS';
export const PRODUCT_LIST_ERROR = 'PRODUCT_LIST_ERROR';
export const PRODUCT_LIST_REQUEST = 'PRODUCT_LIST_REQUEST';

export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS';
export const SINGLE_PRODUCT_ERROR = 'SINGLE_PRODUCT_ERROR';
export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST';
